### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by gotson** [MAIF/cards#2]
Are there plans to translate the cards in English (at least), or other languages ?
Or to provide an easy way for contributors to translate cards ?

**Comment by mathieuancelin** [comment]
Hi @gotson 

as cards are generated from an bunch of JSON files, I guess it could be pretty simple to translate the JSON sources (using PR) and then generate multiple versions of the cards. I'll try to think about something soon

**Comment by gotson** [comment]
Thanks @mathieuancelin, if you decide on a folder structure that could host translations we could start sending PRs indeed.

**Comment by mathieuancelinserli** [comment]
Hey @gotson 

I started working on translation. I changed the structure of the files to be language aware, and I made an automated translation of the cards using google translate. Now everyone is welcome to enhance translations using github PR :)

**Comment by mathieuancelin** [comment]
Yes @gotson, `docs/` is the output of `yarn generator` and yes it should be commited because it is the content of https://maif.github.io/cards/ as it's hosted directly on github pages. 

You can send your PR with `docs/` updated, but it's okay if you only change `src/cards/*` sources, I will generate `docs/` after merging the PR. I think the PR will be clearer this way :)

**Comment by gotson** [comment]
Thanks for the clarification, indeed if it's directly hosted on github it makes sense.

**Comment by gotson** [comment]
Just noticed that in the left menu, the language title it taken from the `lang` attribute of https://github.com/MAIF/cards/blob/master/src/cards/lang.json 
I supposed it's used for other purposes than just display (like translating via Google Translate).

It would be good to have a separate display name, as it's usually a best practice to display the language name in that language itself (for example 日本語 instead of JA for Japanese).

**Comment by mathieuancelin** [comment]
@gotson that's a very good idea indeed ;)

**Comment by gotson** [comment]
I sent a PR for the English translation: #3
