### ISSUE TITLE
[FEATURE REQUEST] Display the recto, hide temporarily the verso

### ISSUE THREAD

**Issue by wikijm** [MAIF/cards#6]
[FR]
Bonjour,

Merci pour le partage de ce projet à la communité.

Je souhaites faire un jeu de carte reprenant les faits marquants d'un voyage à l'étranger.

J'aimerais pouvoir :

1. Tirer une carte de façon aléatoire et afficher son recto
2. Cliquer sur la carte afin d'afficher son verso, juste à droite du verso précédemment affiché
3. Cliquer sur le bouton de tirage aléatoire pour passer à une nouvelle carte
4. Avoir un message d'information une fois l'ensemble de la catégorie de carte passée durant la session en cours

Je sais que ma requête de fonctionnalité ne correspond pas forcément au but initial de votre projet.
Une simple d'aide et d'aiguillage m'irait pour apporter moi-même les éléments demandés :-)

-----------------------------------------------------------------------

[EN]
Hi,

Thank you for sharing this project with the community.

I would like to make a card game with the fun facts of a trip abroad.

I wish I could:
- Randomly draw a card and display its front side
- Click on the map to display its reverse side, just to the right of the previously displayed reverse side
- Click on the random draw button to switch to a new card
- Have an information message once the entire card category has been passed during the current session

I know that my feature request does not necessarily correspond to the initial purpose of your project.
A simple help and referral would be fine:-)

**Comment by desmfr** [comment]
Hello

sorry the value we shared here is the content not the style of the app, as you say being a cards deck generator is not our initial purpose, so we won't work on this way.

**Comment by mathieuancelin** [comment]
but you can still take the code of the generator, change the content of the cards (https://github.com/MAIF/cards/tree/master/src/cards) and add a bit of css and js to make it match your need (hide front or back, notify the end of the category, etc ...)

**Comment by wikijm** [comment]
Hi @desmfr,
I expected this kind of answer, no problem.

@mathieuancelin 
Thank you for this lead, I'll work on it 😉
