### ISSUE TITLE
How to obtain generic cover without icons and/or in an editable format?

### ISSUE THREAD

**Issue by wikijm** [MAIF/cards#7]
[FR]
Bonjour,

Serait-il possible d'obtenir les fonds de carte sans les logos incrustés (et/ou dans un format éditable) ?

Cela permettrait de pouvoir recréer de nouveaux fonds de carte, et notamment ajouter des couleurs pour de nouvelles catégories.

D'avance merci pour votre réponse 😃 

Cordialement,
WikiJM

-------------------------------------------------------------------------------------

[EN]
Hi,

Would it be possible to obtain the card backgrounds without the embedded logos (and/or in an editable format)?

This would make it possible to recreate new background maps, including adding colours for new categories.

Thank you in advance for your answer 😃 

Sincerely,
WikiJM

**Comment by desmfr** [comment]
Hello

background sources can be replaced in cards/src/images/

**Comment by wikijm** [comment]
Hi @desmfr,

I think I understood the location of the different files, but thanks for this confirmation.

My request was to know if it was possible to recover the background cards in one of the following formats:

- .psd   -   Photoshop
- .ai      -   Illustrator
- .svg   -   Vectorial

A rough example for [neutre-cover](https://github.com/MAIF/cards/blob/master/src/images/neutre-cover.png) of what I'm looking for:
![neutre-cover 1](https://user-images.githubusercontent.com/10724809/53894856-23d13880-4031-11e9-8f80-7c913cb53388.png)

**Comment by desmfr** [comment]
Ok, i gonna share our request to our designer.

**Comment by wikijm** [comment]
Thank you @desmfr 😃
