### ISSUE TITLE
Un mode d'emploi ?

### ISSUE THREAD

**Issue by dcz-switcher** [MAIF/cards#9]
Merci beaucoup pour le partage de vos réalisations avec la communauté.
Au delà des cartes elles-mêmes, il serait intéressant d'avoir une présentation de comment vous l'utilisez ?
A quel(s) moment(s) ?
Quel public ?
Quelle animation
...

**Comment by desmfr** [comment]
Bonjour

c'est à but pédagogique avant tout, afin de partager ce qu'on définit comme étant les bonnes pratiques à mettre en oeuvre au sein de nos équipes.

on peut par exemple partager le contnu des cartes au kick off d'une nouvelle équipe et revenir sur les thèmes adéquats lors des point d'échange pour recentrer l'équipe sur les choses essentielles.

on peut aussi s'intéresser au deck à titre individuel dans le cadre d'une "formation", on a pas vraiment de modalités d'usage définies à l'avance en fait :)

l'important c'est que le contenu soit pertinent et puisse guider nos collaborateurs au travers de leur travail et de leur implication ;)

**Comment by dcz-switcher** [comment]
Merci pour ces précisions !
